# What is a Random Number?


# Pseudo Random and True Random.

# Generate Random Number

Generate a random integer from 0 to 100:

In [1]:
from numpy import random

x = random.randint(100)

print(x)

90


# Generate Random Float

Generate a random float from 0 to 1:

In [2]:
from numpy import random

x = random.rand()

print(x)

0.6799362410659588


# Generate Random Array

# Integers

Generate a 1-D array containing 5 random integers from 0 to 100:

In [3]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[66 47 32 47 68]


Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

In [4]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[57 27 78 24 77]
 [69 38 58 59 90]
 [ 2  8 39  6 61]]


# Floats

Generate a 1-D array containing 5 random floats:

In [5]:
from numpy import random

x = random.rand(5)

print(x)

[0.10566706 0.62950977 0.19017503 0.5126248  0.13488687]


Generate a 2-D array with 3 rows, each row containing 5 random numbers:

In [6]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.37870143 0.45689394 0.90692703 0.22842775 0.0814996 ]
 [0.97063469 0.11568663 0.1810842  0.36492452 0.71324594]
 [0.07834685 0.58316187 0.40732212 0.46289444 0.21235384]]


# Generate Random Number From Array

Return one of the values in an array:

In [7]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

9


Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

In [8]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[9 5 3 9 5]
 [3 3 5 9 7]
 [3 3 9 7 3]]
